/**
 * Intune Script Generator
 * Generates PowerShell scripts and metadata for Intune Win32 app deployment
 */

/**
 * Main function to generate all Intune deployment artifacts
 * @param {Object} packagingData - Analysis data from crawler
 * @returns {Object} - Contains all generated scripts and metadata
 */
function generateIntuneScripts(packagingData) {
  const timestamp = new Date().toISOString();
  
  return {
    installScript: generateInstallScript(packagingData, timestamp),
    uninstallScript: generateUninstallScript(packagingData, timestamp),
    detectionScript: generateDetectionScript(packagingData, timestamp),
    metadataJson: generateMetadata(packagingData, timestamp),
    readmeText: generateReadme(packagingData),
    intuneWrapperScript: generateIntuneWinWrapper(packagingData, timestamp)
  };
}

/**
 * Generate Install.ps1
 */
function generateInstallScript(data, timestamp) {
  const appName = data.classification?.baseName || 'Application';
  const version = data.version || 'Unknown';
  const installerFileName = data.filename;
  const installerType = data.installerType;
  
  let installCommand = '';
  
  if (installerType === 'MSI') {
    const silentArgs = data.silentInstallCommand?.match(/msiexec\s+\/i\s+"[^"]+"\s+(.*)/)?.[1] || '/qn /norestart';
    installCommand = [
      '',
      '$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path',
      '$InstallerPath = Join-Path $ScriptDir "' + installerFileName + '"',
      '',
      'if (-not (Test-Path $InstallerPath)) {',
      '    Write-Host "ERROR: Installer not found at $InstallerPath"',
      '    exit 1',
      '}',
      '',
      'Write-Host "Starting installation of ' + appName + ' ' + version + '..."',
      'Write-Host "Installer: $InstallerPath"',
      '',
      '$arguments = "/i `"$InstallerPath`" ' + silentArgs + '"',
      'Write-Host "Running: msiexec.exe $arguments"',
      '',
      '$process = Start-Process "msiexec.exe" -ArgumentList $arguments -Wait -PassThru -NoNewWindow',
      '',
      'if ($process.ExitCode -eq 0) {',
      '    Write-Host "Installation completed successfully."',
      '    exit 0',
      '} elseif ($process.ExitCode -eq 3010) {',
      '    Write-Host "Installation completed successfully. Reboot required."',
      '    exit 0',
      '} else {',
      '    Write-Host "ERROR: Installation failed with exit code $($process.ExitCode)"',
      '    exit $process.ExitCode',
      '}'
    ].join('\n');
  } else if (installerType === 'EXE') {
    const silentArgs = data.silentInstallCommand?.replace(/^"[^"]+"\s*/, '') || '/S';
    installCommand = [
      '',
      '$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path',
      '$InstallerPath = Join-Path $ScriptDir "' + installerFileName + '"',
      '',
      'if (-not (Test-Path $InstallerPath)) {',
      '    Write-Host "ERROR: Installer not found at $InstallerPath"',
      '    exit 1',
      '}',
      '',
      'Write-Host "Starting installation of ' + appName + ' ' + version + '..."',
      'Write-Host "Installer: $InstallerPath"',
      '',
      '$arguments = "' + silentArgs + '"',
      'Write-Host "Running: $InstallerPath $arguments"',
      '',
      '$process = Start-Process -FilePath $InstallerPath -ArgumentList $arguments -Wait -PassThru -NoNewWindow',
      '',
      'if ($process.ExitCode -eq 0) {',
      '    Write-Host "Installation completed successfully."',
      '    exit 0',
      '} else {',
      '    Write-Host "WARNING: Installation exited with code $($process.ExitCode)"',
      '    Write-Host "Some installers return non-zero codes even on success. Verify installation manually."',
      '    exit 0',
      '}'
    ].join('\n');
  } else {
    installCommand = [
      '',
      'Write-Host "ERROR: Unsupported installer type: ' + installerType + '"',
      'Write-Host "Please configure installation manually."',
      'exit 1'
    ].join('\n');
  }

  return [
    '<#',
    '    Generated by: App Packaging Helper (Chrome Extension)',
    '    Purpose: Intune Win32 app deployment - Installation script',
    '    App: ' + appName + ' ' + version,
    '    Installer Type: ' + installerType,
    '    Generated: ' + timestamp,
    '#>',
    installCommand
  ].join('\n');
}

/**
 * Generate Uninstall.ps1
 */
function generateUninstallScript(data, timestamp) {
  const appName = data.classification?.baseName || 'Application';
  const version = data.version || 'Unknown';
  const installerType = data.installerType;
  
  let uninstallCommand = '';
  
  if (installerType === 'MSI') {
    const hasProductCode = data.uninstallCommand?.includes('{') && data.uninstallCommand?.includes('}');
    
    if (hasProductCode) {
      const productCode = data.uninstallCommand.match(/\{[A-F0-9-]+\}/)?.[0] || '{PRODUCT-CODE-HERE}';
      uninstallCommand = [
        '',
        'Write-Host "Starting uninstallation of ' + appName + ' ' + version + '..."',
        '',
        '$ProductCode = "' + productCode + '"',
        '$arguments = "/x $ProductCode /qn /norestart"',
        '',
        'Write-Host "Running: msiexec.exe $arguments"',
        '',
        '$process = Start-Process "msiexec.exe" -ArgumentList $arguments -Wait -PassThru -NoNewWindow',
        '',
        'if ($process.ExitCode -eq 0) {',
        '    Write-Host "Uninstallation completed successfully."',
        '    exit 0',
        '} elseif ($process.ExitCode -eq 1605) {',
        '    Write-Host "Application is not installed. Nothing to uninstall."',
        '    exit 0',
        '} else {',
        '    Write-Host "ERROR: Uninstallation failed with exit code $($process.ExitCode)"',
        '    exit $process.ExitCode',
        '}'
      ].join('\n');
    } else {
      uninstallCommand = [
        '',
        '# NOTE: MSI Product Code not available during generation.',
        '# To find the Product Code after installation, run:',
        '# Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -like "*' + appName + '*" } | Select-Object Name, IdentifyingNumber',
        '',
        'Write-Host "Searching for ' + appName + ' in installed applications..."',
        '',
        '$app = Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -like "*' + appName + '*" }',
        '',
        'if ($app) {',
        '    Write-Host "Found: $($app.Name) - Product Code: $($app.IdentifyingNumber)"',
        '    Write-Host "Starting uninstallation..."',
        '    ',
        '    $arguments = "/x $($app.IdentifyingNumber) /qn /norestart"',
        '    $process = Start-Process "msiexec.exe" -ArgumentList $arguments -Wait -PassThru -NoNewWindow',
        '    ',
        '    if ($process.ExitCode -eq 0) {',
        '        Write-Host "Uninstallation completed successfully."',
        '        exit 0',
        '    } else {',
        '        Write-Host "ERROR: Uninstallation failed with exit code $($process.ExitCode)"',
        '        exit $process.ExitCode',
        '    }',
        '} else {',
        '    Write-Host "Application not found. Nothing to uninstall."',
        '    exit 0',
        '}'
      ].join('\n');
    }
  } else if (installerType === 'EXE') {
    uninstallCommand = [
      '',
      '# NOTE: EXE uninstall command not available from analysis.',
      '# Check the following registry locations for uninstall strings:',
      '# - HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall',
      '# - HKLM:\\SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall',
      '',
      'Write-Host "Searching for ' + appName + ' uninstall information..."',
      '',
      '$uninstallKeys = @(',
      '    "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\*",',
      '    "HKLM:\\SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\*"',
      ')',
      '',
      '$uninstallString = $null',
      '',
      'foreach ($key in $uninstallKeys) {',
      '    $app = Get-ItemProperty $key -ErrorAction SilentlyContinue | Where-Object { $_.DisplayName -like "*' + appName + '*" }',
      '    if ($app -and $app.UninstallString) {',
      '        $uninstallString = $app.UninstallString',
      '        Write-Host "Found uninstall string: $uninstallString"',
      '        break',
      '    }',
      '}',
      '',
      'if ($uninstallString) {',
      '    Write-Host "Starting uninstallation..."',
      '    # Add silent switches if needed (e.g., /S, /VERYSILENT)',
      '    $process = Start-Process -FilePath "cmd.exe" -ArgumentList "/c $uninstallString /S" -Wait -PassThru -NoNewWindow',
      '    ',
      '    if ($process.ExitCode -eq 0) {',
      '        Write-Host "Uninstallation completed successfully."',
      '        exit 0',
      '    } else {',
      '        Write-Host "Uninstallation exited with code $($process.ExitCode)"',
      '        exit 0',
      '    }',
      '} else {',
      '    Write-Host "WARNING: Uninstall string not found. Manual uninstallation may be required."',
      '    exit 0',
      '}'
    ].join('\n');
  } else {
    uninstallCommand = [
      '',
      'Write-Host "ERROR: Unsupported installer type: ' + installerType + '"',
      'Write-Host "Please configure uninstallation manually."',
      'exit 1'
    ].join('\n');
  }

  return [
    '<#',
    '    Generated by: App Packaging Helper (Chrome Extension)',
    '    Purpose: Intune Win32 app deployment - Uninstallation script',
    '    App: ' + appName + ' ' + version,
    '    Installer Type: ' + installerType,
    '    Generated: ' + timestamp,
    '#>',
    uninstallCommand
  ].join('\n');
}

/**
 * Generate Detection.ps1
 */
function generateDetectionScript(data, timestamp) {
  const appName = data.classification?.baseName || 'Application';
  const version = data.version || 'Unknown';
  const detectionRule = data.detectionRule;
  
  let detectionLogic = '';
  
  if (detectionRule?.type === 'file' && detectionRule.path) {
    const detectionPath = detectionRule.path.replace(/%ProgramFiles%/g, '$env:ProgramFiles');
    detectionLogic = [
      '',
      '# File-based detection',
      '$detectionPath = "' + detectionPath + '"',
      '',
      'Write-Host "Checking for application at: $detectionPath"',
      '',
      'if (Test-Path $detectionPath) {',
      '    Write-Host "Application detected: $detectionPath"',
      '    exit 0',
      '} else {',
      '    Write-Host "Application NOT detected."',
      '    exit 1',
      '}'
    ].join('\n');
  } else if (detectionRule?.type === 'registry') {
    detectionLogic = [
      '',
      '# Registry-based detection',
      '# NOTE: Registry path needs to be configured based on actual installation',
      '',
      '$registryPaths = @(',
      '    "HKLM:\\SOFTWARE\\' + appName + '",',
      '    "HKLM:\\SOFTWARE\\WOW6432Node\\' + appName + '"',
      ')',
      '',
      '$found = $false',
      '',
      'foreach ($path in $registryPaths) {',
      '    if (Test-Path $path) {',
      '        Write-Host "Application detected at: $path"',
      '        $found = $true',
      '        break',
      '    }',
      '}',
      '',
      'if ($found) {',
      '    exit 0',
      '} else {',
      '    Write-Host "Application NOT detected."',
      '    exit 1',
      '}'
    ].join('\n');
  } else if (data.installerType === 'MSI') {
    detectionLogic = [
      '',
      '# MSI Product Code detection',
      '# NOTE: For MSI installers, Intune can automatically detect using Product Code.',
      '# This script is provided as a fallback for file-based detection.',
      '',
      '# Check common installation paths',
      '$possiblePaths = @(',
      '    "$env:ProgramFiles\\' + appName + '",',
      '    "$env:ProgramFiles\\' + appName + '\\' + appName + '.exe",',
      '    "${env:ProgramFiles(x86)}\\' + appName + '",',
      '    "${env:ProgramFiles(x86)}\\' + appName + '\\' + appName + '.exe"',
      ')',
      '',
      '$found = $false',
      '',
      'foreach ($path in $possiblePaths) {',
      '    if (Test-Path $path) {',
      '        Write-Host "Application detected at: $path"',
      '        $found = $true',
      '        break',
      '    }',
      '}',
      '',
      'if ($found) {',
      '    exit 0',
      '} else {',
      '    Write-Host "Application NOT detected."',
      '    exit 1',
      '}'
    ].join('\n');
  } else {
    detectionLogic = [
      '',
      '# Generic detection logic',
      '# Check common installation paths',
      '',
      '$appName = "' + appName + '"',
      '$possiblePaths = @(',
      '    "$env:ProgramFiles\\$appName",',
      '    "${env:ProgramFiles(x86)}\\$appName",',
      '    "$env:ProgramData\\$appName"',
      ')',
      '',
      '$found = $false',
      '',
      'foreach ($path in $possiblePaths) {',
      '    if (Test-Path $path) {',
      '        Write-Host "Application detected at: $path"',
      '        $found = $true',
      '        break',
      '    }',
      '}',
      '',
      'if ($found) {',
      '    exit 0',
      '} else {',
      '    Write-Host "Application NOT detected."',
      '    exit 1',
      '}'
    ].join('\n');
  }

  return [
    '<#',
    '    Generated by: App Packaging Helper (Chrome Extension)',
    '    Purpose: Intune Win32 app deployment - Detection script',
    '    App: ' + appName + ' ' + version,
    '    Generated: ' + timestamp,
    '    ',
    '    Note: This detection script should be tested and customized based on ',
    '    the actual installation location of the application.',
    '#>',
    detectionLogic
  ].join('\n');
}

/**
 * Generate metadata.json
 */
function generateMetadata(data, timestamp) {
  const metadata = {
    appName: data.classification?.baseName || 'Application',
    version: data.version || 'Unknown',
    installerType: data.installerType,
    installerFileName: data.filename,
    silentInstallCommand: data.silentInstallCommand,
    uninstallCommand: data.uninstallCommand,
    detectionRule: data.detectionRule,
    confidence: data.confidence,
    warnings: data.warnings || [],
    sourcePages: data.sourcePages || [],
    generatedAt: timestamp,
    generatedBy: 'App Packaging Helper Chrome Extension'
  };
  
  return JSON.stringify(metadata, null, 2);
}

/**
 * Generate README.txt
 */
function generateReadme(data) {
  const appName = data.classification?.baseName || 'Application';
  const version = data.version || 'Unknown';
  const installerType = data.installerType;
  
  const warningSection = data.warnings && data.warnings.length > 0 
    ? '\nWARNINGS:\n' + data.warnings.map(w => '- ' + w).join('\n') + '\n'
    : '';
  
  const lowConfidenceWarning = data.confidence?.overall === 'LOW'
    ? '\n⚠ LOW CONFIDENCE DETECTED\nThe generated scripts are based on generic patterns and may require customization.\nAlways test in a non-production environment first.\n'
    : '';
  
  const msiDetection = installerType === 'MSI'
    ? 'For MSI installers, you can use:\n- Rule type: MSI\n- MSI product code: [Extract from ' + data.filename + ']\n\nAlternatively, use custom detection:'
    : 'Use custom detection script:';

  return [
    '========================================',
    'Intune Win32 App Deployment Package',
    'Generated by: App Packaging Helper',
    '========================================',
    '',
    'Application: ' + appName,
    'Version: ' + version,
    'Installer Type: ' + installerType,
    'Installer File: ' + data.filename,
    '',
    '========================================',
    'PACKAGE CONTENTS',
    '========================================',
    '',
    '1. Install.ps1          - PowerShell installation script',
    '2. Uninstall.ps1        - PowerShell uninstallation script',
    '3. Detection.ps1        - PowerShell detection script',
    '4. metadata.json        - Application metadata and configuration',
    '5. Create-IntunePackage.ps1 - Helper script to create .intunewin package',
    '6. README.txt           - This file',
    '',
    '========================================',
    'DEPLOYMENT STEPS',
    '========================================',
    '',
    'STEP 1: PREPARE SOURCE FILES',
    '----------------------------',
    '1. Create a source folder (e.g., C:\\IntunePackages\\' + appName + ')',
    '2. Copy the following files to the source folder:',
    '   - ' + data.filename + ' (your installer)',
    '   - Install.ps1',
    '   - Uninstall.ps1',
    '',
    'STEP 2: CREATE .INTUNEWIN PACKAGE',
    '----------------------------------',
    'Option A: Using the provided wrapper script',
    '   1. Ensure IntuneWinAppUtil.exe is available',
    '   2. Run: .\\Create-IntunePackage.ps1 -SourceFolder "C:\\IntunePackages\\' + appName + '" -SetupFile "' + data.filename + '" -OutputFolder "C:\\IntunePackages\\Output"',
    '',
    'Option B: Manual process',
    '   1. Download IntuneWinAppUtil.exe from Microsoft',
    '   2. Run: IntuneWinAppUtil.exe -c "C:\\IntunePackages\\' + appName + '" -s "' + data.filename + '" -o "C:\\IntunePackages\\Output"',
    '',
    'This creates: ' + data.filename + '.intunewin',
    '',
    'STEP 3: UPLOAD TO INTUNE',
    '-------------------------',
    '1. Sign in to Microsoft Intune admin center (https://intune.microsoft.com)',
    '2. Navigate to: Apps > Windows > Add > Windows app (Win32)',
    '3. Click "Select app package file" and upload the .intunewin file',
    '',
    'STEP 4: CONFIGURE APP INFORMATION',
    '----------------------------------',
    '- Name: ' + appName,
    '- Description: [Add description]',
    '- Publisher: [Add publisher name]',
    '- App Version: ' + version,
    '',
    'STEP 5: CONFIGURE PROGRAM SETTINGS',
    '-----------------------------------',
    'Install command:',
    '    powershell.exe -ExecutionPolicy Bypass -File .\\Install.ps1',
    '',
    'Uninstall command:',
    '    powershell.exe -ExecutionPolicy Bypass -File .\\Uninstall.ps1',
    '',
    'Install behavior: System',
    'Device restart behavior: Determine behavior based on return codes (or configure as needed)',
    '',
    'STEP 6: CONFIGURE REQUIREMENTS',
    '-------------------------------',
    '- Operating system architecture: 64-bit (or as appropriate)',
    '- Minimum operating system: Windows 10 1607 (or as needed)',
    '',
    'STEP 7: CONFIGURE DETECTION RULES',
    '----------------------------------',
    msiDetection,
    '- Rule type: Use a custom detection script',
    '- Script file: Detection.ps1',
    '- Run script as 32-bit process on 64-bit clients: No',
    '- Enforce script signature check: No',
    '',
    'STEP 8: ASSIGN TO GROUPS',
    '-------------------------',
    '1. Add assignments (Required/Available/Uninstall)',
    '2. Select target groups',
    '3. Review and create',
    '',
    '========================================',
    'IMPORTANT NOTES',
    '========================================',
    warningSection,
    'CONFIDENCE LEVELS:',
    '- Install Command: ' + (data.confidence?.installCommand || 'UNKNOWN'),
    '- Uninstall Command: ' + (data.confidence?.uninstallCommand || 'UNKNOWN'),
    '- Detection: ' + (data.confidence?.detection || 'UNKNOWN'),
    lowConfidenceWarning,
    'TESTING RECOMMENDATIONS:',
    '1. Test installation on a clean VM/test machine',
    '2. Verify the application installs correctly',
    '3. Test the detection script returns exit code 0 when app is installed',
    '4. Test uninstallation removes the application completely',
    '5. Verify detection script returns exit code 1 after uninstallation',
    '',
    'TROUBLESHOOTING:',
    '- Check Intune logs: C:\\ProgramData\\Microsoft\\IntuneManagementExtension\\Logs',
    '- Review script execution in Event Viewer',
    '- Test scripts manually before deploying via Intune',
    '',
    'For more information:',
    'https://learn.microsoft.com/en-us/mem/intune/apps/apps-win32-add',
    '',
    '========================================',
    'Generated: ' + new Date().toISOString(),
    '========================================'
  ].join('\n');
}

/**
 * Generate Create-IntunePackage.ps1 wrapper script
 */
function generateIntuneWinWrapper(data, timestamp) {
  const appName = data.classification?.baseName || 'Application';
  
  return [
    '<#',
    '    Generated by: App Packaging Helper (Chrome Extension)',
    '    Purpose: Helper script to create .intunewin package',
    '    App: ' + appName,
    '    Generated: ' + timestamp,
    '    ',
    '    This script wraps IntuneWinAppUtil.exe to simplify package creation.',
    '#>',
    '',
    'param(',
    '    [Parameter(Mandatory=$true)]',
    '    [string]$SourceFolder,',
    '    ',
    '    [Parameter(Mandatory=$true)]',
    '    [string]$SetupFile,',
    '    ',
    '    [Parameter(Mandatory=$true)]',
    '    [string]$OutputFolder,',
    '    ',
    '    [Parameter(Mandatory=$false)]',
    '    [string]$IntuneWinAppUtilPath = ".\\IntuneWinAppUtil.exe"',
    ')',
    '',
    'Write-Host "========================================" -ForegroundColor Cyan',
    'Write-Host "Intune Package Creator" -ForegroundColor Cyan',
    'Write-Host "========================================" -ForegroundColor Cyan',
    'Write-Host ""',
    '',
    '# Validate source folder',
    'if (-not (Test-Path $SourceFolder)) {',
    '    Write-Host "ERROR: Source folder not found: $SourceFolder" -ForegroundColor Red',
    '    exit 1',
    '}',
    '',
    '# Validate setup file exists in source folder',
    '$setupFilePath = Join-Path $SourceFolder $SetupFile',
    'if (-not (Test-Path $setupFilePath)) {',
    '    Write-Host "ERROR: Setup file not found: $setupFilePath" -ForegroundColor Red',
    '    exit 1',
    '}',
    '',
    '# Validate IntuneWinAppUtil.exe',
    'if (-not (Test-Path $IntuneWinAppUtilPath)) {',
    '    Write-Host "ERROR: IntuneWinAppUtil.exe not found at: $IntuneWinAppUtilPath" -ForegroundColor Red',
    '    Write-Host ""',
    '    Write-Host "Please download IntuneWinAppUtil.exe from:" -ForegroundColor Yellow',
    '    Write-Host "https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool" -ForegroundColor Yellow',
    '    exit 1',
    '}',
    '',
    '# Create output folder if it doesn\'t exist',
    'if (-not (Test-Path $OutputFolder)) {',
    '    Write-Host "Creating output folder: $OutputFolder"',
    '    New-Item -ItemType Directory -Path $OutputFolder -Force | Out-Null',
    '}',
    '',
    'Write-Host "Source Folder: $SourceFolder" -ForegroundColor Green',
    'Write-Host "Setup File: $SetupFile" -ForegroundColor Green',
    'Write-Host "Output Folder: $OutputFolder" -ForegroundColor Green',
    'Write-Host ""',
    '',
    'Write-Host "Creating .intunewin package..." -ForegroundColor Yellow',
    '',
    '$arguments = "-c `"$SourceFolder`" -s `"$SetupFile`" -o `"$OutputFolder`" -q"',
    '',
    '$process = Start-Process -FilePath $IntuneWinAppUtilPath -ArgumentList $arguments -Wait -PassThru -NoNewWindow',
    '',
    'if ($process.ExitCode -eq 0) {',
    '    Write-Host ""',
    '    Write-Host "========================================" -ForegroundColor Green',
    '    Write-Host "SUCCESS!" -ForegroundColor Green',
    '    Write-Host "========================================" -ForegroundColor Green',
    '    Write-Host ""',
    '    Write-Host "Package created: $OutputFolder\\$SetupFile.intunewin" -ForegroundColor Green',
    '    Write-Host ""',
    '    Write-Host "Next steps:" -ForegroundColor Cyan',
    '    Write-Host "1. Sign in to Microsoft Intune admin center" -ForegroundColor White',
    '    Write-Host "2. Navigate to Apps > Windows > Add > Windows app (Win32)" -ForegroundColor White',
    '    Write-Host "3. Upload the .intunewin file" -ForegroundColor White',
    '    Write-Host "4. Configure using the provided Install.ps1, Uninstall.ps1, and Detection.ps1" -ForegroundColor White',
    '    exit 0',
    '} else {',
    '    Write-Host ""',
    '    Write-Host "ERROR: Package creation failed with exit code $($process.ExitCode)" -ForegroundColor Red',
    '    exit $process.ExitCode',
    '}'
  ].join('\n');
}

module.exports = {
  generateIntuneScripts
};
